// <auto-generated />
namespace Fuel.DAL.EF6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CarsOnly : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CarsOnly));
        
        string IMigrationMetadata.Id
        {
            get { return "201611290953189_CarsOnly"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
